env:
  es2021: true
  node: true
extends: eslint:recommended
plugins:
  - coffeescript
  - import
parser: eslint-plugin-coffeescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/order: error
